AppBundle\Entity\Competences:
    type: entity
    table: competences
    indexes:
        competences_fk0:
            columns:
                - id_metier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        idMetier:
            targetEntity: Metiers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_metier:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
