AppBundle\Entity\MaitresDeStage:
    type: entity
    table: maitres_de_stage
    indexes:
        id_utilisateur:
            columns:
                - id_utilisateur
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomEntreprise:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: nom_entreprise
    manyToOne:
        idUtilisateur:
            targetEntity: Utilisateurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_utilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
