AppBundle\Entity\Metiers:
    type: entity
    table: metiers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        photoPath:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: photo_path
        definition:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
