AppBundle\Entity\Stagiaires:
    type: entity
    table: stagiaires
    indexes:
        id_utilisateur:
            columns:
                - id_utilisateur
        id_utilisateur_2:
            columns:
                - id_utilisateur
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        activation:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    manyToOne:
        idUtilisateur:
            targetEntity: Utilisateurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_utilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
