AppBundle\Entity\StagesStagiaires:
    type: entity
    table: stages_stagiaires
    indexes:
        stages_stagiaires_fk1:
            columns:
                - id_stagiaire
        id_stage:
            columns:
                - id_stage
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idStage:
            targetEntity: Stages
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_stage:
                    referencedColumnName: id
            orphanRemoval: false
        idStagiaire:
            targetEntity: Stagiaires
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_stagiaire:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
