AppBundle\Entity\Utilisateurs:
    type: entity
    table: utilisateurs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        passwordHash:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: password_hash
        role:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
