# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   app.cors  _listener:
       class: AppBundle\EventListener\CorsListener
       tags:
          - { name: kernel.event_listener, event: kernel.response,   method: onKernelResponse }

   auth_token_user_provider:
       class: AppBundle\Security\AuthTokenUserProvider
       arguments: ["@auth_token_repository", "@user_repository"]
       public:    false

   auth_token_repository:
       class:   Doctrine\ORM\EntityManager
       factory: ["@doctrine.orm.entity_manager", "getRepository"]
       arguments: ["AppBundle:AuthToken"]

   user_repository:
       class:   Doctrine\ORM\EntityManager
       factory: ["@doctrine.orm.entity_manager", "getRepository"]
       arguments: ["AppBundle:Utilisateurs"]

   auth_token_authenticator:
       class:     AppBundle\Security\AuthTokenAuthenticator
       arguments: ["@security.http_utils"]
       public:    false